events {}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;
        server_name localhost;

        # Указываем корень прямо в папку HTML, где лежат login.html и register.html
        root /usr/share/nginx/html/HTML;
        index index.html login.html;

        # Главная страница сайта
        location / {
            try_files $uri $uri/ =404;
        }

        # Если фронтенд запрашивает стили или картинки (../css/style.css),
        # мы перенаправляем Nginx на один уровень выше, в корень frontend
        location ~* ^\/(css|images|design|js)\/ {
            root /usr/share/nginx/html;
            try_files $uri =404;
        }

        # Прокси для бэкенда
        location /api/ {
            proxy_pass http://backend:8000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}

